using System.Globalization;
using System.Text;

namespace GspkProbe;

/// <summary>A clamped B-spline record in binary64, as the source stores it.</summary>
internal sealed record Spline(int Degree, double[] Knots, double[][] Points)
{
    internal double[] At(double u)
    {
        int p = Degree, n = Points.Length - 1;
        int k = u >= Knots[n + 1] ? n : Array.FindLastIndex(Knots, t => t <= u);
        if (k > n) k = n;
        var d = Enumerable.Range(0, p + 1).Select(j => Points[k - p + j].ToArray()).ToArray();
        for (int r = 1; r <= p; r++)
            for (int j = p; j >= r; j--)
            {
                int i = k - p + j;
                double width = Knots[i + p - r + 1] - Knots[i];
                double a = width > 0 ? (u - Knots[i]) / width : 0;
                for (int c = 0; c < 2; c++) d[j][c] = (1 - a) * d[j - 1][c] + a * d[j][c];
            }
        return d[p];
    }

    /// <summary>Boehm single knot insertion (Piegl and Tiller A5.1 with r = 1).</summary>
    internal Spline Insert(double u)
    {
        int p = Degree, n = Points.Length - 1;
        int k = Array.FindLastIndex(Knots, t => t <= u);
        var q = new double[n + 2][];
        for (int i = 0; i <= n + 1; i++)
        {
            if (i <= k - p) q[i] = Points[i].ToArray();
            else if (i >= k + 1) q[i] = Points[i - 1].ToArray();
            else
            {
                double a = (u - Knots[i]) / (Knots[i + p] - Knots[i]);
                q[i] = new[] { a * Points[i][0] + (1 - a) * Points[i - 1][0], a * Points[i][1] + (1 - a) * Points[i - 1][1] };
            }
        }
        var knots = Knots.Take(k + 1).Append(u).Concat(Knots.Skip(k + 1)).ToArray();
        return new(p, knots, q);
    }

    internal string Body() =>
        "degree " + Degree + " knots [" + string.Join(", ", Knots.Select(Fixtures.Number)) + "] points [" +
        string.Join(", ", Points.Select(p => "(" + Fixtures.Number(p[0]) + ", " + Fixtures.Number(p[1]) + ")")) + "]";
}

internal sealed record ProfileText(string Name, Spline Upper, Spline Lower, string Closure);

internal static class Fixtures
{
    internal static readonly Spline SectionAUpper = new(5,
        new[] { 0, 0, 0, 0, 0, 0, 0.3333333333333333, 0.6666666666666666, 1, 1, 1, 1, 1, 1 },
        new[] { new[] { 0d, 0 }, new[] { 0, 0.025 }, new[] { 0.15, 0.055 }, new[] { 0.35, 0.065 }, new[] { 0.55, 0.05 }, new[] { 0.75, 0.03 }, new[] { 0.9, 0.01 }, new[] { 1d, 0 } });
    internal static Spline SectionALower => Mirror(SectionAUpper);

    internal static Spline Mirror(Spline s) => s with { Points = s.Points.Select(p => new[] { p[0], -p[1] }).ToArray() };

    /// <summary>Shortest round-trip decimal without exponent notation (the grammar's number form).</summary>
    internal static string Number(double value)
    {
        string r = value.ToString("R", CultureInfo.InvariantCulture);
        if (!r.Contains('E')) return r;
        decimal? d = null;
        try { d = decimal.Parse(r, NumberStyles.Float, CultureInfo.InvariantCulture); } catch (OverflowException) { }
        Guard(d is not null && (double)d.Value == value, "number " + r + " has no exact plain decimal form");
        return d!.Value.ToString(CultureInfo.InvariantCulture);
    }

    internal static void Guard(bool condition, string message) { if (!condition) throw new InvalidOperationException(message); }

    internal static string Foil(double chordMm, IEnumerable<ProfileText> profiles, string sections)
    {
        string c = Number(chordMm);
        var text = new StringBuilder();
        text.Append("foildsl \"4.0\"\n# GSPK probe fixture (generated by docs/proof/m12c-certificate-spike/probe; see verdict.md for provenance).\n");
        text.Append("foil \"GSPK fixture\" {\n  units mm\n  half_span 450 mm\n  evaluator \"cfdw-cv\" \"2\"\n  symmetry mirror_y\n  planform {\n");
        text.Append("    leading cv { degree 3 knots [0, 0, 0, 0, 0.25, 0.5, 0.75, 1, 1, 1, 1] points [(0, 0), (0.1, 0), (0.3, 0), (0.5, 0), (0.7, 0), (0.9, 0), (1, 0)] }\n");
        text.Append("    trailing cv { degree 3 knots [0, 0, 0, 0, 0.25, 0.5, 0.75, 1, 1, 1, 1] points [(0, " + c + "), (0.1, " + c + "), (0.3, " + c + "), (0.5, " + c + "), (0.7, " + c + "), (0.9, " + c + "), (1, " + c + ")] }\n  }\n");
        text.Append("  dihedral cv { degree 3 knots [0, 0, 0, 0, 0.25, 0.5, 0.75, 1, 1, 1, 1] points [(0, 0), (0.1, 0), (0.3, 0), (0.5, 0), (0.7, 0), (0.9, 0), (1, 0)] }\n");
        text.Append("  twist cv { degree 3 knots [0, 0, 0, 0, 0.25, 0.5, 0.75, 1, 1, 1, 1] points [(0, 0), (0.1, 0), (0.3, -0.25), (0.5, -0.5), (0.7, -1), (0.9, -1.5), (1, -2)] }\n");
        text.Append("  thickness cv { degree 3 knots [0, 0, 0, 0, 0.25, 0.5, 0.75, 1, 1, 1, 1] points [(0, 0.12), (0.1, 0.12), (0.3, 0.12), (0.5, 0.12), (0.7, 0.12), (0.9, 0.12), (1, 0.12)] }\n");
        text.Append("  profiles {\n");
        foreach (var p in profiles)
        {
            text.Append("    profile \"" + p.Name + "\" {\n");
            text.Append("      upper cv { " + p.Upper.Body() + " }\n");
            text.Append("      lower cv { " + p.Lower.Body() + " }\n");
            text.Append("      closure " + p.Closure + "\n    }\n");
        }
        text.Append("  }\n  sections { " + sections + " }\n}\n");
        return text.ToString();
    }

    /// <summary>§3.4 Control → Anchor on one surface: find u* with x(u*) = P.x by bisection, insert it to multiplicity
    /// p by Boehm, then move the interpolated vertex and both handles by Δy = P.y − C(u*).y.</summary>
    internal static (Spline Result, double U, double DeltaY, int Vertex) ControlToAnchor(Spline s, int vertex)
    {
        double targetX = s.Points[vertex][0], targetY = s.Points[vertex][1];
        double lo = 0, hi = 1;
        for (int i = 0; i < 200 && hi - lo > 0; i++)
        {
            double mid = (lo + hi) / 2;
            if (mid == lo || mid == hi) break;
            if (s.At(mid)[0] < targetX) lo = mid; else hi = mid;
        }
        double u = Math.Abs(s.At(lo)[0] - targetX) <= Math.Abs(s.At(hi)[0] - targetX) ? lo : hi;
        foreach (var knot in s.Knots.Distinct())
            if (Math.Abs(knot - u) <= 1e-12 * Math.Max(1, Math.Abs(knot))) u = knot;
        int existing = s.Knots.Count(k => k == u);
        var result = s;
        for (int i = existing; i < s.Degree; i++) result = result.Insert(u);
        var point = result.At(u);
        int index = -1; double best = double.MaxValue;
        for (int i = 0; i < result.Points.Length; i++)
        {
            double distance = Math.Abs(result.Points[i][0] - point[0]) + Math.Abs(result.Points[i][1] - point[1]);
            if (distance < best) { best = distance; index = i; }
        }
        Guard(best < 1e-12, "the inserted vertex does not interpolate C(u*)");
        double dy = targetY - point[1];
        var points = result.Points.Select(p => p.ToArray()).ToArray();
        for (int i = index - 1; i <= index + 1; i++) points[i][1] += dy;
        return (result with { Points = points }, u, dy, index);
    }

    internal static ProfileText XEdited(string name, int vertex, double dx)
    {
        var upper = SectionAUpper with { Points = SectionAUpper.Points.Select(p => p.ToArray()).ToArray() };
        upper.Points[vertex][0] += dx;
        return new(name, upper, Mirror(upper), "closed");
    }
}
