using System.Diagnostics;
using System.Globalization;
using System.Diagnostics.Metrics;
using CfdWorkbench.Analysis.NeuralFoil;
using CfdWorkbench.Core;

namespace CfdWorkbench.Analysis.Tests;

// Fixtures: NeuralFoilCaseTable is a copy of SPIKE-ANA-1 cases.tsv/python.tsv (CST parameters fed straight to the
// network; it does not exercise CstFit). NeuralFoilE2eTable is generated by Fixtures/neuralfoil/generate_e2e.py from
// section ordinates through Python's own CST fit (neuralfoil 0.3.2, aerosandbox 4.2.9, xxxlarge).
// Platform: macOS arm64 measured. Windows: not measured, pending (tracked in docs/proof/a3c-polar-source).

internal static class NeuralFoilTests
{
    internal static void Run()
    {
        AnalysisChecks.Check("NeuralFoil_Fidelity_Python032", Fidelity);
        AnalysisChecks.Check("NeuralFoil_EndToEnd_SectionToPolar_Python032", EndToEnd);
        AnalysisChecks.Check("NeuralFoil_CorruptWeights_Refused", CorruptWeights);
        AnalysisChecks.Check("NeuralFoil_CstFit_RecoversSection", CstFitRecoversSection);
        AnalysisChecks.Check("NeuralFoil_Source_ProducesPolarSample", ProducesPolarSample);
        AnalysisChecks.Check("NeuralFoil_Source_NoncomputableNamesReason", NoncomputableNamesReason);
        AnalysisChecks.Check("NeuralFoil_Envelope_Alpha_OutsideTraining_NonComputable", () => Refused(40, 500000, 4, "naca0012", false, "alpha"));
        AnalysisChecks.Check("NeuralFoil_Envelope_Re_OutsideTraining_NonComputable", () => Refused(0, 1e11, 4, "naca0012", false, "Re"));
        AnalysisChecks.Check("NeuralFoil_Envelope_Ncrit_OutsideTraining_NonComputable", () => Refused(0, 500000, 25, "naca0012", false, "Ncrit"));
        AnalysisChecks.Check("NeuralFoil_Envelope_Alpha_InsideTraining_ComputedFlagged", () => Flagged(10, 500000, 4, "alpha"));
        AnalysisChecks.Check("NeuralFoil_Envelope_Re_InsideTraining_ComputedFlagged", () => Flagged(0, 50000, 4, "Re"));
        AnalysisChecks.Check("NeuralFoil_Envelope_Ncrit_InsideTraining_ComputedFlagged", () => Flagged(0, 500000, 12, "Ncrit"));
        AnalysisChecks.Check("NeuralFoil_Envelope_Ncrit_IntermediateValue_Flagged", () => Flagged(0, 500000, 5, "Ncrit"));
        AnalysisChecks.Check("NeuralFoil_Envelope_InsideBracket_NotFlagged", InsideBracketNotFlagged);
        AnalysisChecks.Check("NeuralFoil_Family_EditedNaca0012_LosesValidatedFamily", EditedLosesFamily);
        AnalysisChecks.Check("NeuralFoil_Family_CatalogNaca0012_DerivedNotLabelled", CatalogDerivedFamily);
        AnalysisChecks.Check("NeuralFoil_Envelope_CstResidual", () => Refused(0, 500000, 4, "naca0012", true, "CST"));
        AnalysisChecks.Check("NeuralFoil_Envelope_OutsideValidatedBracket", OutsideBracket);
        AnalysisChecks.Check("NeuralFoil_Confidence_Low_ComputedFlaggedNeverRefused", LowConfidenceAdvisory);
        AnalysisChecks.Check("NeuralFoil_Telemetry_EmittedOnNormalPath", Telemetry);
        AnalysisChecks.Check("NeuralFoil_InferenceCost", InferenceCost);
    }

    private static void Fidelity()
    {
        NeuralFoilNetwork network = NeuralFoilNetwork.FromEmbedded();
        double maxDifference = 0;
        foreach (NeuralFoilCaseTable.Case row in NeuralFoilCaseTable.Rows)
        {
            var parameters = new CstParameters(row.Upper, row.Lower, row.Leading, row.Trailing);
            NeuralFoilPrediction value = network.Predict(parameters, row.Alpha, row.Reynolds, row.Ncrit);
            double[] expected = [row.Confidence, row.Cl, row.Cd, row.Cm, row.XtrUpper, row.XtrLower];
            double[] actual = [value.AnalysisConfidence, value.Cl, value.Cd, value.Cm, value.XtrUpper, value.XtrLower];
            for (int i = 0; i < expected.Length; i++)
            {
                double difference = Math.Abs(expected[i] - actual[i]);
                maxDifference = Math.Max(maxDifference, difference);
                if (difference > 1e-10) throw new Exception($"{row.Name} output {i} difference {difference:G17}");
            }
        }
        Console.WriteLine("NeuralFoil fidelity max difference " + maxDifference.ToString("G17", CultureInfo.InvariantCulture));
    }

    // Tolerance 2e-3 absolute on every output. Python fits the sampled section through its own Airfoil path, so the CST
    // weights differ slightly from the C# least squares; observed maximum 7.8e-4 (Cl, naca4412) on macOS arm64.
    // This is a fit-path difference, not the 1e-10 network arithmetic of NeuralFoil_Fidelity_Python032.
    private const double EndToEndTolerance = 2e-3;

    private static void EndToEnd()
    {
        NeuralFoilNetwork network = NeuralFoilNetwork.FromEmbedded();
        double[] x = Enumerable.Range(0, 200).Select(i => 0.5 * (1 - Math.Cos(Math.PI * i / 199))).ToArray();
        double maxDifference = 0;
        foreach (NeuralFoilE2eTable.Case row in NeuralFoilE2eTable.Rows)
        {
            (double[] upper, double[] lower) = NeuralFoilE2eTable.Sections[row.Foil];
            CstFitResult fit = CstFit.Fit(new NeuralFoilSection(new string('c', 64), row.Foil, x, upper, lower));
            NeuralFoilPrediction value = network.Predict(fit.Parameters, row.Alpha, row.Reynolds, row.Ncrit);
            double[] expected = [row.Confidence, row.Cl, row.Cd, row.Cm, row.XtrUpper, row.XtrLower];
            double[] actual = [value.AnalysisConfidence, value.Cl, value.Cd, value.Cm, value.XtrUpper, value.XtrLower];
            for (int i = 0; i < expected.Length; i++)
            {
                double difference = Math.Abs(expected[i] - actual[i]);
                maxDifference = Math.Max(maxDifference, difference);
                if (difference > EndToEndTolerance)
                    throw new Exception($"{row.Foil} a{row.Alpha} output {i} difference {difference:G17}");
            }
        }
        Console.WriteLine("NeuralFoil end-to-end max difference " + maxDifference.ToString("G17", CultureInfo.InvariantCulture));
    }

    private static void CorruptWeights()
    {
        using Stream stream = typeof(NeuralFoilNetwork).Assembly.GetManifestResourceStream(NeuralFoilNetwork.ResourceName)!;
        using var copy = new MemoryStream();
        stream.CopyTo(copy);
        byte[] bytes = copy.ToArray();
        bytes[^1] ^= 1;
        try { NeuralFoilNetwork.FromBytes(bytes); }
        catch (ContractError error) when (error.Code == "ANA-POLAR-WEIGHTS-HASH") { return; }
        throw new Exception("corrupted weights were accepted");
    }

    private static NeuralFoilSection Section(bool badResidual, string family)
    {
        var cst = family switch
        {
            "naca2412" => NeuralFoilCaseTable.Rows[3],
            "naca4412" => NeuralFoilCaseTable.Rows[4],
            _ => NeuralFoilCaseTable.Rows[0]
        };
        var parameters = new CstParameters(cst.Upper, cst.Lower, cst.Leading, cst.Trailing);
        double[] x = Enumerable.Range(0, 200).Select(i => 0.5 * (1 - Math.Cos(Math.PI * i / 199))).ToArray();
        double[] upper = x.Select(value => CstFit.Ordinate(parameters, value, upper: true)).ToArray();
        double[] lower = x.Select(value => CstFit.Ordinate(parameters, value, upper: false)).ToArray();
        if (badResidual) upper[100] += 0.03;
        return new NeuralFoilSection(new string('a', 64), family, x, upper, lower);
    }

    private static void CstFitRecoversSection()
    {
        NeuralFoilSection section = Section(false, "naca2412");
        CstFitResult fit = CstFit.Fit(section);
        if (fit.MaxResidual > 1e-8 || fit.RmsResidual > 1e-8)
            throw new Exception($"exact CST section fit residual {fit.MaxResidual:G17}");
        var expected = NeuralFoilCaseTable.Rows[3];
        if (Math.Abs(fit.Parameters.Upper[2] - expected.Upper[2]) > 1e-6 ||
            Math.Abs(fit.Parameters.TrailingEdge - expected.Trailing) > 1e-6)
            throw new Exception("CST coefficient recovery changed");
    }

    private static void ProducesPolarSample()
    {
        NeuralFoilSection section = Section(false, "naca0012");
        IPolarSource source = new NeuralFoilPolarSource(hash => hash == section.ProfileHash ? section : null);
        var water = new WaterRecord(15, 0, 999, 1e-6, 1000, "fixture", new string('b', 64));
        PolarSample? sample = source.Sample(section.ProfileHash, 1000000, 4, 0, water, CancellationToken.None);
        var expected = NeuralFoilCaseTable.Rows[1];
        if (sample is null || Math.Abs(sample.Cl!.Value - expected.Cl) > 1e-8 ||
            Math.Abs(sample.Cd!.Value - expected.Cd) > 1e-8 ||
            Math.Abs(sample.Confidence!.Value - expected.Confidence) > 1e-8 ||
            sample.MethodVersion != NeuralFoilNetwork.MethodVersion || sample.WaterHash.Length != 64)
            throw new Exception("polar source lost a coefficient, confidence, or method key");
    }

    private static void NoncomputableNamesReason()
    {
        NeuralFoilSection section = Section(false, "naca0012");
        IPolarSource source = new NeuralFoilPolarSource(_ => section);
        var water = new WaterRecord(15, 0, 999, 1e-6, 1000, "fixture", new string('b', 64));
        try { source.Sample(section.ProfileHash, 500000, 4, 30, water, CancellationToken.None); }
        catch (ContractError error) when (error.Code == "ANA-POLAR-NONCOMPUTABLE" && error.Reason?.Contains("alpha") == true)
        {
            return;
        }
        throw new Exception("IPolarSource silently dropped a non-computable point");
    }

    private static void Refused(double alpha, double reynolds, double ncrit, string family, bool badResidual, string reason)
    {
        var source = new NeuralFoilPolarSource(_ => Section(badResidual, family));
        NeuralFoilEvaluation result = source.Evaluate(Section(badResidual, family), alpha, reynolds, ncrit, CancellationToken.None);
        if (result.Computable || result.Reason is null || !result.Reason.Contains(reason, StringComparison.OrdinalIgnoreCase))
            throw new Exception("point was not marked non-computable: " + result.Reason);
        if (!double.IsFinite(result.CstResidualMax)) throw new Exception("CST residual missing");
    }

    private static void Flagged(double alpha, double reynolds, double ncrit, string axis)
    {
        NeuralFoilSection section = Section(false, "naca0012");
        var source = new NeuralFoilPolarSource(_ => section);
        NeuralFoilEvaluation result = source.Evaluate(section, alpha, reynolds, ncrit, CancellationToken.None);
        if (!result.Computable || result.Prediction is null) throw new Exception("point inside the training range was refused: " + result.Reason);
        if (!result.OutsideValidatedBracket ||
            !result.OutsideBracketReasons.Any(text => text.Contains(axis, StringComparison.OrdinalIgnoreCase)))
            throw new Exception("outside-bracket flag for " + axis + " missing: " + string.Join("; ", result.OutsideBracketReasons));
        if (!double.IsFinite(result.CstResidualMax)) throw new Exception("CST residual missing");
    }

    private static void InsideBracketNotFlagged()
    {
        NeuralFoilSection section = Section(false, "naca0012");
        var source = new NeuralFoilPolarSource(_ => section);
        NeuralFoilEvaluation result = source.Evaluate(section, 3, 500000, 4, CancellationToken.None);
        if (!result.Computable || result.OutsideValidatedBracket)
            throw new Exception("validated point was flagged: " + string.Join("; ", result.OutsideBracketReasons));
    }

    // A smooth 0.4 percent chord bump on the upper surface, labelled "naca0012": the CST fit absorbs it (small residual),
    // so only the geometry comparison can notice that the section is no longer the validated one.
    private static void EditedLosesFamily()
    {
        NeuralFoilSection pure = Section(false, "naca0012");
        double[] upper = pure.X.Select((x, i) => pure.Upper[i] + 0.004 * Math.Exp(-Math.Pow((x - 0.4) / 0.15, 2))).ToArray();
        var edited = new NeuralFoilSection(pure.ProfileHash, "naca0012", pure.X, upper, pure.Lower);
        var source = new NeuralFoilPolarSource(_ => edited);
        NeuralFoilEvaluation result = source.Evaluate(edited, 3, 500000, 4, CancellationToken.None);
        Console.WriteLine("MEASURE naca0012 match tolerance " + Naca0012Reference.MatchTolerance.ToString("G3", CultureInfo.InvariantCulture)
            + " spike-open " + Naca0012Reference.MaxOrdinateDifference(CstFit.Fit(pure).Parameters).ToString("G3", CultureInfo.InvariantCulture)
            + " edited " + Naca0012Reference.MaxOrdinateDifference(CstFit.Fit(edited).Parameters).ToString("G3", CultureInfo.InvariantCulture)
            + " editedFitResidual " + result.CstResidualMax.ToString("G3", CultureInfo.InvariantCulture));
        if (!result.Computable) throw new Exception("edited section was refused instead of flagged: " + result.Reason);
        if (!result.OutsideBracketReasons.Any(text => text.Contains("NACA 0012", StringComparison.Ordinal)))
            throw new Exception("edited NACA 0012 kept the validated family: " + string.Join("; ", result.OutsideBracketReasons));
    }

    private static void CatalogDerivedFamily()
    {
        CatalogEntry entry = Catalog.Load().Single(item => item.Id == "naca-0012");
        NeuralFoilSection section = Naca0012Reference.FromSelig(new string('d', 64), "caller-label-ignored", entry.Coordinates!);
        var source = new NeuralFoilPolarSource(_ => section);
        NeuralFoilEvaluation result = source.Evaluate(section, 3, 500000, 4, CancellationToken.None);
        if (!result.Computable || result.OutsideValidatedBracket)
            throw new Exception("catalog NACA 0012 was not recognised from its geometry: " + string.Join("; ", result.OutsideBracketReasons));
    }

    private static void OutsideBracket()
    {
        var source = new NeuralFoilPolarSource(_ => Section(false, "naca0012"));
        NeuralFoilEvaluation result = source.Evaluate(Section(false, "naca2412"), 3, 500000, 5, CancellationToken.None);
        if (!result.Computable || !result.OutsideValidatedBracket || result.Prediction is null)
            throw new Exception("outside-bracket prediction or flag missing");
    }

    private static void LowConfidenceAdvisory()
    {
        // Python: alpha 27, Re 1e3, Ncrit 0 on NACA 0012 gives analysis_confidence 6.7e-6 (inside the training range).
        NeuralFoilSection section = Section(false, "naca0012");
        var source = new NeuralFoilPolarSource(_ => section);
        NeuralFoilEvaluation result = source.Evaluate(section, 27, 1000, 0, CancellationToken.None);
        if (!result.Computable || result.Prediction is null) throw new Exception("low-confidence point was refused: " + result.Reason);
        if (result.Prediction.AnalysisConfidence >= NeuralFoilPolarSource.LowConfidenceBelow)
            throw new Exception("fixture point is not low confidence: " + result.Prediction.AnalysisConfidence);
        if (!result.LowConfidence || result.ConfidenceWarning is null) throw new Exception("low-confidence flag missing");
        string text = result.ConfidenceWarning;
        if (!text.Contains("advisory", StringComparison.OrdinalIgnoreCase) ||
            !text.Contains("not an accuracy", StringComparison.OrdinalIgnoreCase))
            throw new Exception("warning does not say the confidence is advisory and not an accuracy statement: " + text);
        var water = new WaterRecord(15, 0, 999, 1e-6, 1000, "fixture", new string('b', 64));
        PolarSample? sample = source.Sample(section.ProfileHash, 1000, 0, 27, water, CancellationToken.None);
        if (sample?.Confidence is not { } carried || carried >= NeuralFoilPolarSource.LowConfidenceBelow)
            throw new Exception("sample dropped the advisory confidence");
        NeuralFoilEvaluation fine = source.Evaluate(section, 0, 500000, 4, CancellationToken.None);
        if (fine.LowConfidence || fine.ConfidenceWarning is not null) throw new Exception("high-confidence point was flagged");
    }

    private static void Telemetry()
    {
        int durations = 0, calls = 0;
        using var listener = new MeterListener();
        listener.InstrumentPublished = (instrument, self) =>
        {
            if (instrument.Meter.Name == "CfdWorkbench.Analysis.NeuralFoil") self.EnableMeasurementEvents(instrument);
        };
        listener.SetMeasurementEventCallback<double>((instrument, _, _, _) =>
        {
            if (instrument.Name == "neuralfoil.evaluate.duration_ms") durations++;
        });
        listener.SetMeasurementEventCallback<long>((instrument, _, _, _) =>
        {
            if (instrument.Name == "neuralfoil.evaluate.calls") calls++;
        });
        listener.Start();
        NeuralFoilSection section = Section(false, "naca0012");
        var source = new NeuralFoilPolarSource(_ => section);
        source.Evaluate(section, 0, 500000, 4, CancellationToken.None);
        if (durations != 1 || calls != 1) throw new Exception($"telemetry missing: durations={durations}, calls={calls}");
    }

    private static void InferenceCost()
    {
        var row = NeuralFoilCaseTable.Rows[0];
        var parameters = new CstParameters(row.Upper, row.Lower, row.Leading, row.Trailing);
        NeuralFoilNetwork network = NeuralFoilNetwork.FromEmbedded();
        for (int i = 0; i < 3; i++) network.Predict(parameters, 0, 500000, 4);
        var watch = Stopwatch.StartNew();
        for (int i = 0; i < 10; i++) network.Predict(parameters, 0, 500000, 4);
        watch.Stop();
        Console.WriteLine("COST NeuralFoil_InferencePerCall " + (watch.Elapsed.TotalMilliseconds / 10).ToString("F3", CultureInfo.InvariantCulture));
    }
}
