"""Generate NeuralFoilE2eTable.cs: section ordinates -> Python NeuralFoil 0.3.2 xxxlarge outputs.

Run from the worktree root with ~/dev/sim/.venv/bin/python (no system install).
Provenance: neuralfoil 0.3.2, aerosandbox 4.2.9, model xxxlarge, weights source SHA-256
94638c04bca3c303515cf0c2944e2b09f587818cbd2860183bd85f2fbeeef428.
Section ordinates are sampled at 200 cosine stations exactly as SPIKE-ANA-1/reference.py does; Python then fits
them through its own Airfoil -> KulfanAirfoil path, so the C# CstFit is exercised against Python's fit.
"""

import importlib.metadata
from pathlib import Path

import aerosandbox as asb
import neuralfoil as nf
import numpy as np

OUT = Path(__file__).resolve().parent / "NeuralFoilE2eTable.cs"
FOILS = ("naca0012", "naca2412", "naca4412")
POINTS = ((3.0, 500000.0, 4.0), (-4.0, 1000000.0, 9.0))


def literal(values):
    return "[" + ", ".join(repr(float(v)) for v in values) + "]"


def main():
    x = 0.5 * (1 - np.cos(np.linspace(0, np.pi, 200)))
    rows, sections = [], []
    for name in FOILS:
        foil = asb.Airfoil(name).normalize()
        upper = foil.local_camber(x) + foil.local_thickness(x) / 2
        lower = foil.local_camber(x) - foil.local_thickness(x) / 2
        sections.append(f'        ["{name}"] = ({literal(upper)}, {literal(lower)}),')
        # Selig order: upper trailing edge to leading edge, then lower leading edge to trailing edge.
        coords = np.concatenate((
            np.stack((x[::-1], upper[::-1]), axis=1),
            np.stack((x[1:], lower[1:]), axis=1)))
        fitted = asb.Airfoil(name + "-sampled", coordinates=coords).normalize().to_kulfan_airfoil(n_weights_per_side=8)
        for alpha, reynolds, ncrit in POINTS:
            aero = nf.get_aero_from_kulfan_parameters(
                fitted.kulfan_parameters, alpha, reynolds, n_crit=ncrit, model_size="xxxlarge")
            keys = ("analysis_confidence", "CL", "CD", "CM", "Top_Xtr", "Bot_Xtr")
            values = ", ".join(repr(float(aero[k][0])) for k in keys)
            rows.append(f'        new("{name}", {alpha!r}, {reynolds!r}, {ncrit!r}, {values}),')
    text = (
        "namespace CfdWorkbench.Analysis.Tests;\n\n"
        "// Generated by generate_e2e.py (same folder). neuralfoil "
        + importlib.metadata.version("neuralfoil") + ", aerosandbox "
        + importlib.metadata.version("aerosandbox") + ", model xxxlarge.\n"
        "// Section ordinates at 200 cosine stations -> Python's own CST fit -> Python network outputs.\n"
        "internal static class NeuralFoilE2eTable\n{\n"
        "    internal sealed record Case(string Foil, double Alpha, double Reynolds, double Ncrit,\n"
        "        double Confidence, double Cl, double Cd, double Cm, double XtrUpper, double XtrLower);\n\n"
        "    internal static readonly Dictionary<string, (double[] Upper, double[] Lower)> Sections = new()\n    {\n"
        + "\n".join(sections) + "\n    };\n\n"
        "    internal static readonly Case[] Rows =\n    [\n" + "\n".join(rows).rstrip(",") + "\n    ];\n}\n")
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
