#!/usr/bin/env python3
"""Compare the as-built run with the hooked copy's constant-rule rows: status, reason, admission work, query work and
the query result hash must be equal, or the instrumented copy is not a faithful measurement device.

Usage: python3 neutrality.py <proof-dir> <stage>   (writes output/neutrality-<stage>.md; exit 1 on any difference)
"""
import json
import pathlib
import sys

root, stage = pathlib.Path(sys.argv[1]), sys.argv[2]
built = json.loads((root / "output" / f"{stage}-as-built.json").read_text())
hooked = [r for r in json.loads((root / "output" / f"{stage}-hooked.json").read_text()) if r["Rule"] == "256 (as built)"]
keys = ["Status", "Reason", "Work", "QueryWorkMax", "QueryHash", "AdmitAtoms"]
lines = [f"# Neutrality check, {stage}", "",
         "As-built Core vs the hooked copy at its defaults (rule 256, bound 1e6). Equal means the copy measures what Core does.", "",
         "| Fixture | Spans | " + " | ".join(keys) + " | Equal |", "|---|---|" + "---|" * (len(keys) + 1)]
bad = 0
for a, h in zip(built, hooked, strict=True):
    # Query columns exist in the as-built run only for a certified row; for a refused row the hooked copy's query
    # columns come from its lifted-bound run, which the as-built Core cannot make.
    compared = keys if a["Status"] == "Certified" else ["Status", "Reason", "Work"]
    same = all(a[k] == h[k] for k in compared) and a["Fixture"] == h["Fixture"] and a["Spans"] == h["Spans"]
    bad += not same
    lines.append(f"| {a['Fixture']} | {a['Spans']} | " + " | ".join(str(a[k]) for k in keys) + f" | {'yes' if same else 'NO'} |")
lines += ["", f"{len(built) - bad} of {len(built)} rows equal."]
front = ["---", f"id: proof-blend-certificate-budget-neutrality-{stage}",
         f"title: \"Blend budget probe - neutrality check, {stage} (generated)\"", "type: proof-pack", "status: in-review",
         "owner: \"@timianmalloo\"", "phase: design", "tags: [certificate, blend, budget, probe, generated, ruling-73]",
         "links:", "  - { to: proof-blend-certificate-budget, rel: depends-on }", "review-by: 2026-11-30",
         "summary: >-", "  Generated by probe/neutrality.py: the hooked Core copy at its defaults equals the as-built Core, row by row.",
         "review-suggested: []", "---", ""]
(root / "output" / f"neutrality-{stage}.md").write_text("\n".join(front + lines) + "\n")
print(f"{len(built) - bad} of {len(built)} rows equal")
sys.exit(1 if bad else 0)
