#!/usr/bin/env python3
"""Summarise the hooked runs: maximum spans per rule and fixture family, the op-model decomposition, and the
result-hash equality across rules. Usage: python3 summarize.py <proof-dir>  (writes output/summary.md)"""
import collections
import json
import pathlib
import sys

root = pathlib.Path(sys.argv[1])
rows = []
for stage in ("stage1", "stage2", "four"):
    rows += json.loads((root / "output" / f"{stage}-hooked.json").read_text())
rules = list(dict.fromkeys(r["Rule"] for r in rows))
families = list(dict.fromkeys(r["Fixture"] for r in rows))


def within_limits(r):
    """Certified once the all-query bound is lifted, and inside 1e9 bit-work and 1 s for admission and every query."""
    return (r["StatusNoOpBound"] == "Certified" and r["Work"] < 1e9 and r["AdmitMs"] <= 1000
            and r["QueryWorkMax"] < 1e9 and r["QueryMsMax"] <= 1000 and r["QueryRefusals"] == 0)


def max_spans(family, rule, test):
    spans = sorted((r["Spans"], test(r)) for r in rows if r["Fixture"] == family and r["Rule"] == rule)
    best = None
    for s, ok in spans:
        if not ok:
            break
        best = s
    return ("none" if best is None else str(best)) + f" (of {spans[0][0]}-{spans[-1][0]})"


out = ["# Summary (generated by probe/summarize.py)", "",
       "Maximum spans per surface that certify for every span count from the family's smallest up to it.", "",
       "## A. As built limits (node budget, all-query bound 1e6, work 1e9, 1 s)", "",
       "| Fixture family | " + " | ".join(rules) + " |", "|---|" + "---|" * len(rules)]
for f in families:
    out.append(f"| {f} | " + " | ".join(max_spans(f, ru, lambda r: r["Status"] == "Certified") for ru in rules) + " |")
out += ["", "## B. Work 1e9 and 1 s only (all-query bound lifted; admission and every query)", "",
        "| Fixture family | " + " | ".join(rules) + " |", "|---|" + "---|" * len(rules)]
for f in families:
    out.append(f"| {f} | " + " | ".join(max_spans(f, ru, within_limits) for ru in rules) + " |")

# Op model: ops = base(curves, spans) + 2*N*32 + 6*N*(N+1). The base is ops minus that blend term.
out += ["", "## C. All-query op count decomposition (base = ops - 64 N - 6 N (N + 1))", "",
        "| Fixture family | Spans | Rule | N | Ops | Base |", "|---|---|---|---|---|---|"]
bases = collections.defaultdict(set)
for r in rows:
    if r["Operations"] > 0 and r["Rule"] == "max(256, 48 s)":
        n = r["Nodes"]
        base = r["Operations"] - 64 * n - 6 * n * (n + 1)
        bases[r["Fixture"]].add(base - 32 * r["Spans"])
        if r["Spans"] in (1, 3, 5, 6, 8, 16):
            out.append(f"| {r['Fixture']} | {r['Spans']} | {r['Rule']} | {n} | {r['Operations']:,} | {base:,} |")
out += ["", "Base minus 32 x spans, per family (one value means the base is exactly constant + 32 per span): " +
        "; ".join(f"{k}: {sorted(v)}" for k, v in bases.items())]

hashes = collections.defaultdict(set)
for r in rows:
    if r["QueryHash"]:
        hashes[(r["Fixture"], r["Spans"])].add(r["QueryHash"])
differ = [k for k, v in hashes.items() if len(v) > 1]
out += ["", "## D. Does the node budget change any answer?", "",
        f"Fixtures with a query sweep under two or more rules: {sum(1 for v in hashes.values())}; "
        f"fixtures whose 23 SectionAt results differ between rules: {len(differ)} {differ if differ else ''}.", "",
        "## E. Maxima over every hooked row", "",
        f"- admission work max {max(r['Work'] for r in rows):,} bit-work; admission ms max {max(r['AdmitMs'] for r in rows):.0f}",
        f"- query work max {max(r['QueryWorkMax'] for r in rows):,} bit-work; query ms max {max(r['QueryMsMax'] for r in rows):.0f}",
        f"- query nodes used: min {min(r['QueryNodesMax'] for r in rows if r['QueryNodesMax'])}, max {max(r['QueryNodesMax'] for r in rows)}",
        f"- max T0 relative gap max {max(r['QueryGapMax'] for r in rows):.3g}; query refusals {sum(r['QueryRefusals'] for r in rows)}",
        f"- fit residual max (synthetic fixtures) {max(r['FitResidual'] for r in rows):.3g} chord"]
front = ["---", "id: proof-blend-certificate-budget-summary", "title: \"Blend budget probe - summary (generated)\"",
         "type: proof-pack", "status: in-review", "owner: \"@timianmalloo\"", "phase: design",
         "tags: [certificate, blend, budget, probe, generated, ruling-73]", "links:",
         "  - { to: proof-blend-certificate-budget, rel: depends-on }", "review-by: 2026-11-30", "summary: >-",
         "  Generated by probe/summarize.py from the hooked runs: maximum spans per rule, op-count decomposition, hash equality.",
         "review-suggested: []", "---", ""]
(root / "output" / "summary.md").write_text("\n".join(front + out) + "\n")
print("\n".join(out))
